### PR TITLE
Create Random Projects.

### PR DESCRIPTION
**Pull request by KatlehoGxagxa**
I explore creating apps from internet inspiration.

### CODE REVIEW

**Comment by Skhendle** [comment]
Why create random projects when you can work on one you like or contribute to open source

**Comment by KatlehoGxagxa** [comment]
Coding muscle exercise. + seeing which branch of coding I like most.

**Comment by Skhendle** [comment]
You are to old for doing that this way. Solve problems in differenr branches using code would be betterAnyways just sharing my 2 cents

**Comment by KatlehoGxagxa** [comment]
Thanks for the tip!

**Pull request closed without merging**
